### ISSUE TITLE
getting started, where to put .lua files

### ISSUE THREAD

**Issue by MaNGOS-Rumors** [azerothcore/mod-eluna-lua-engine#15]
in the readme is not clear where to put the lua script files
where is the lua_scripts directory?

**Comment by Viste** [comment]
as i remember it is declare in conf file
and by defalts its bin/worldserver/lua_scripts

**Comment by FrancescoBorzi** [comment]
can anyone please update the readme accordingly?

**Comment by FrancescoBorzi** [comment]
@AyaseCore

**Comment by AyaseCore** [comment]
> can anyone please update the readme accordingly?

Of course. :)
I'm busy with my work. Not much time to maintain it.
I hope to have more friends to make it more perfect.
@FrancescoBorzi

**Comment by mehdikhody** [comment]
Hi, I'm using an ubuntu server and there is no `worldserver` directory in `bin` folder.
what should I do ?

**Comment by Helias** [comment]
I think that the `lua_scripts` directory should be under `bin`
