### ISSUE TITLE
warning: the use of `tmpnam' is dangerous, better use `mkstemp'

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-eluna-lua-engine#17]
```
../../../modules/mod-eluna-lua-engine/lualib/liblualib.a(loslib.c.o): In function `os_tmpname':
loslib.c:(.text+0x86c): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
```

???

**Comment by BarbzYHOOL** [comment]
@Rochet2 ??

**Comment by Viste** [comment]
```
#if defined(LUA_USE_MKSTEMP)
#include <unistd.h>
#define LUA_TMPNAMBUFSIZE	32
#define lua_tmpnam(b,e) { \
        strcpy(b, "/tmp/lua_XXXXXX"); \
        e = mkstemp(b); \
        if (e != -1) close(e); \
        e = (e == -1); }

#elif !defined(lua_tmpnam)

#define LUA_TMPNAMBUFSIZE	L_tmpnam
#define lua_tmpnam(b,e)		{ e = (tmpnam(b) == NULL); }

#endif
````
we can drop this defines and this part of code
```
#define LUA_TMPNAMBUFSIZE	L_tmpnam
#define lua_tmpnam(b,e)		{ e = (tmpnam(b) == NULL); }``` 
to remove warning

**Comment by Rochet2** [comment]
Can define use linux and mac instead.
https://github.com/azerothcore/mod-eluna-lua-engine/blob/93dd4b5f285e0d64a584835582e439d04cd4a2de/lualib/luaconf.h#L43-L59

**Comment by BarbzYHOOL** [comment]
i'd just copy that code rochet ? if so i'll try when i think about it

**Comment by Viste** [comment]
@BarbzYHOOL no you just pass -DLUA_USE_LINUX for Eluna(  https://github.com/azerothcore/mod-eluna-lua-engine/blob/master/cmake/after_load_cmake_modules.cmake#L6 ) and then when you build you  get  -DLUA_USE_LINUX(whats include) LUA_USE_POSIX  whats include LUA_USE_MKSTEMP whats define usage mkstemp

**Comment by BarbzYHOOL** [comment]
oh ok, thank you, when i try i'll update the readme then

**Comment by BarbzYHOOL** [comment]
it was really not clear what to do, I tried to put the variables directly in the command, ofc didn't work

so I added `add_definitions(-DLUA_USE_LINUX)` here https://github.com/azerothcore/mod-eluna-lua-engine/blob/master/cmake/after_load_cmake_modules.cmake#L6 and then:

```
../../../modules/mod-eluna-lua-engine/lualib/liblualib.a(loslib.c.o): In function `os_tmpname':
loslib.c:(.text+0x86c): warning: the use of `tmpnam' is dangerous, better use `mkstemp'

```

Same exact message

What to do?

**Comment by Rochet2** [comment]
Testing fix here: https://travis-ci.org/azerothcore/mod-eluna-lua-engine/builds/632430185?utm_source=github_status&utm_medium=notification
