### ISSUE TITLE
Suggestion: rename to mod-eluna

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-eluna-lua-engine#18]
Seems more fitting and less wordy

Second suggestion: rename "LuaEngine/" to "eluna/"

**Comment by Viste** [comment]
1st ok
2nd not

**Comment by Stoabrogga** [comment]
I'd leave the name as it is. There's no real benefit, but it can cause problems with forks and scripts (e.g. the Travis scripts in the main repo have to be adapted to the new name). I also had some problems in the past because of renamed beastmaster and autobalance modules.

**Comment by BarbzYHOOL** [comment]
i'll do it one day then
