### ISSUE TITLE
Compilation Error (SpellAuraEffects.cpp)

### ISSUE THREAD

**Issue by iThorgrim-hub** [azerothcore/mod-eluna-lua-engine#24]
Hello i have this Error :

![image](https://user-images.githubusercontent.com/58987080/73765875-75b89c00-4775-11ea-8995-16f88a5777b1.png)

With Eluna : https://github.com/azerothcore/mod-eluna-lua-engine/commit/11933a73f8387466622aea70ac34e6b8de648666

With AzerothCore : https://github.com/azerothcore/azerothcore-wotlk/commit/3f0739f1c9a5289444ff9d62834b7ceb38879ba9

**Comment by Rochet2** [comment]
Will be fixed in https://github.com/azerothcore/azerothcore-wotlk/pull/2636
Test it to get it fixed faster :)

**Comment by BarbzYHOOL** [comment]
> PS. the change done to eluna was meant to break build so that ppl will update to fix issues.

lol which change? nice trick if serious

**Comment by Rochet2** [comment]
> lol which change? nice trick if serious

The logic in a hook was invalid and the code was in core code (see PR linked above).
So to force people fix their code in core the return value was removed from the hook (https://github.com/ElunaLuaEngine/Eluna/commit/570a45b7031b86c60d256a25b36e4ca43a156674) and thus everyone gets an error when trying to compile the code that was wrong when using latest eluna.
