### ISSUE TITLE
'out-of-line definition of 'GetFieldName' does not match any declaration in 'ResultSet''

### ISSUE THREAD

**Issue by LucasGitDev** [azerothcore/mod-eluna-lua-engine#28]
##### SMALL DESCRIPTION:

After downloading eluna-mod I tried to recompile "<cmake ../ -DCMAKE_INSTALL_PREFIX=/home/noob/azeroth-server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DTOOLS=0 -DSCRIPTS=1 -DWITH_WARNINGS=1 -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror">" and when I used 'sudo make -j 6' I got the image error

![img issue](https://user-images.githubusercontent.com/44501407/83158213-e3008c00-a0da-11ea-8751-e850afc88bf7.jpg)

https://ibb.co/tm3tjgK

##### EXPECTED BLIZZLIKE BEHAVIOUR:

before the error was normal

##### CURRENT BEHAVIOUR:

just don't recompile

##### STEPS TO REPRODUCE THE PROBLEM:

1. Install mod-eluna from https://github.com/azerothcore/mod-eluna-lua-engine
2. Try recompile using: cmake ../ -DCMAKE_INSTALL_PREFIX=/home/noob/azeroth-server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DTOOLS=0 -DSCRIPTS=1 -DWITH_WARNINGS=1 -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror"
3. Use: sudo make -j 6
4. got the error

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

2743874e5da893c18f6ae19f88dcf944cf4cfc8b

##### OPERATING SYSTEM:

Ubuntu 18.04

##### MODULES:

https://github.com/azerothcore/mod-eluna-lua-engine

##### OTHER CUSTOMIZATIONS:

no other

**Comment by FrancescoBorzi** [comment]
moved

**Comment by LucasGitDev** [comment]
did eluna-mod cause this?

**Comment by Kitzunu** [comment]
@Rochet2

**Comment by SamuelGogarty** [comment]
no fix yet?

**Comment by Rochet2** [comment]
Is this occurring only for one person?
I cannot reproduce it on windows. I downloaded latest core, Eluna-module and Eluna. Then I compiled and all succeeded with default settings.
Also travis is unable to reproduce the issue as seen here: https://github.com/azerothcore/azerothcore-wotlk/runs/722973823

I suggest you make sure you have latest core, eluna-module and Eluna.

**Comment by SamuelGogarty** [comment]
> Is this occurring only for one person?
> I cannot reproduce it on windows. I downloaded latest core, Eluna-module and Eluna. Then I compiled and all succeeded with default settings.
> Also travis is unable to reproduce the issue as seen here: https://github.com/azerothcore/azerothcore-wotlk/runs/722973823
> 
> I suggest you make sure you have latest core, eluna-module and Eluna.

It builds fine on windows, this seems to be a linux specific (maybe mac osx?) issue.

**Comment by Kitzunu** [comment]
afaik AzerothCore doesn't even build on Mac

**Comment by Rochet2** [comment]
@SamuelGogarty Are you having the same problem or are you just commenting on the issue?

**Comment by SamuelGogarty** [comment]
> @SamuelGogarty Are you having the same problem or are you just commenting on the issue?

i am having the same issue, also on the same OS as OP

**Comment by SamuelGogarty** [comment]
> afaik AzerothCore doesn't even build on Mac

there  is official build documentation for mac osx.

**Comment by Helias** [comment]
I think that the problem is about how much the new compiler considers `char*` and `std::string` , now they `different`.

Analyzing the function:
```C++
#ifdef ELUNA
char* ResultSet::GetFieldName(uint32 index) const
{
    ASSERT(index < _fieldCount);
    return _fields[index].name;
}
#endif
```
It returns `_fields[index].name;` that is a `std::string`, so if you change `char*` into `std::string` it does not complain.

Here the fix: https://github.com/azerothcore/azerothcore-wotlk/pull/3103

**Comment by Helias** [comment]
I forgot to say, that I am using:
```
clang and clang++ 6.0.0
gcc and g++ 7.5.0
```
