### ISSUE TITLE
Build error with Eluna Lua module

### ISSUE THREAD

**Issue by sbeehre** [azerothcore/mod-eluna-lua-engine#29]
When i put the mod-eluna-lua-engine module in my modules folder and try to build azerothcore i get the following error

[ 16%] Building CXX object src/common/CMakeFiles/common.dir/Database/Transaction.cpp.o
/home/wowserver/azerothcore/src/common/Database/QueryResult.cpp:189:24: fatal error: out-of-line
      definition of 'GetFieldName' does not match any declaration in 'ResultSet'
std::string ResultSet::GetFieldName(uint32 index) const
                       ^~~~~~~~~~~~
1 error generated.
src/common/CMakeFiles/common.dir/build.make:777: recipe for target 'src/common/CMakeFiles/common.dir/Database/QueryResult.cpp.o' failed
make[2]: *** [src/common/CMakeFiles/common.dir/Database/QueryResult.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1116: recipe for target 'src/common/CMakeFiles/common.dir/all' failed
make[1]: *** [src/common/CMakeFiles/common.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

If remove the module i can build azerothcore just fine

**Comment by Rochet2** [comment]
This looks like an issue that was already fixed in a PR.
Which azerothcore and mod-eluna-lua-engine commit are you using?

**Comment by Rochet2** [comment]
Related: https://github.com/azerothcore/azerothcore-wotlk/pull/3103

**Comment by Helias** [comment]
@sbeehre can you write here your commit hash of your azerothcore version?

**Comment by sbeehre** [comment]
#ifndef __REVISION_H__
#define __REVISION_H__
 #define _REVISION                  ""
 #define _HASH                      "d50793535e0a"
 #define _DATE                      "2020-08-10 08:11:15 +0000"
 #define _BRANCH                    "master"
 #define VER_COMPANYNAME_STR        "AzerothCore"
 #define VER_LEGALCOPYRIGHT_STR     "AzerothCore"
 #define VER_FILEVERSION            0,0,0
 #define VER_FILEVERSION_STR        "d50793535e0a 2020-08-10 08:11:15 +0000 (master branch)"
 #define VER_PRODUCTVERSION         VER_FILEVERSION
 #define VER_PRODUCTVERSION_STR     VER_FILEVERSION_STR
#endif // __REVISION_H__

**Comment by Rochet2** [comment]
@sbeehre please execute the following three commands from a console in your azerothcore source folder and post us back the output.

```bash
git rev-parse HEAD
(cd modules/mod-eluna-lua-engine && git rev-parse HEAD)
(cd modules/mod-eluna-lua-engine/LuaEngine && git rev-parse HEAD)

```

These commands should print the commits of azerothcore, the eluna module and the lua engine that the module uses.

**Comment by sbeehre** [comment]
thanks i will do that and report back

**Comment by sbeehre** [comment]
This is in order

d50793535e0a0bdd0e4a5de475d855532e7d1a8f

3419e76486752f9fd72fdf390b45485ab4ab9caa

31f4cfd98c6c22ac14d3cb5a642382a3a23d4df8

**Comment by sbeehre** [comment]
This is in order

d50793535e0a0bdd0e4a5de475d855532e7d1a8f
 
3419e76486752f9fd72fdf390b45485ab4ab9caa
 
31f4cfd98c6c22ac14d3cb5a642382a3a23d4df8

**Comment by sbeehre** [comment]
Ok here are the results

git rev-parse HEAD
d50793535e0a0bdd0e4a5de475d855532e7d1a8f

cd modules/mod-eluna-lua-engine && git rev-parse HEAD
2aba9a4c051bf0d60547f0b41053f8ef573503f8

cd modules/mod-eluna-lua-engine/LuaEngine && git rev-parse HEAD
2aba9a4c051bf0d60547f0b41053f8ef573503f8

**Comment by sbeehre** [comment]
```
git rev-parse HEAD
d50793535e0a0bdd0e4a5de475d855532e7d1a8f

cd modules/mod-eluna-lua-engine && git rev-parse HEAD
2aba9a4c051bf0d60547f0b41053f8ef573503f8

cd modules/mod-eluna-lua-engine/LuaEngine && git rev-parse HEAD
2aba9a4c051bf0d60547f0b41053f8ef573503f8
```

**Comment by Rastrian** [comment]
Reverse the commit https://github.com/azerothcore/azerothcore-wotlk/pull/3103/commits/bd4143f0a0c9f93af545c56d6d6fca5a7a68138d and the eluna module work fine

**Comment by Helias** [comment]
I can build it normally, @Rastrian did you try to update to the latest version Eluna and AzerothCore?

**Comment by Rastrian** [comment]
> I can build it normally, @Rastrian did you try to update to the latest version Eluna and AzerothCore?

Yeah i tried using Windows and CentOS with Docker and have this same issue, i think its a problem with Docker build, but its seems fixed reversing this commit which i have quoted

**Comment by sbeehre** [comment]
> 
> 
> Reverse the commit [azerothcore/azerothcore-wotlk@bd4143f](https://github.com/azerothcore/azerothcore-wotlk/commit/bd4143f0a0c9f93af545c56d6d6fca5a7a68138d) and the eluna module work fine

Thanks Rastrian how do i do that exactly? im new to using git etc

**Comment by kurigvin** [comment]
Не работает на новой реве AC
