### ISSUE TITLE
compile issue on latest commit d29a1a3

### ISSUE THREAD

**Issue by mfranciscojr** [azerothcore/mod-eluna-lua-engine#3]
Hi,

I'm having an issue compiling this with the latest commit, with previous commit i'm able to compile without issue.

System Ubuntu Server 16.04

First Compile.
Logs
[ 27%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/BattlegroundMgr.cpp.o
/azerothcore-wotlk/src/server/game/Battlegrounds/BattlegroundMgr.cpp:38:23: fatal error: LuaEngine.h: No such file or directory
compilation terminated.
src/server/game/CMakeFiles/game.dir/build.make:710: recipe for target 'src/server/game/CMakeFiles/game.dir/Battlegrounds/BattlegroundMgr.cpp.o' failed
make[2]: *** [src/server/game/CMakeFiles/game.dir/Battlegrounds/BattlegroundMgr.cpp.o] Error 1
CMakeFiles/Makefile2:973: recipe for target 'src/server/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/server/game/CMakeFiles/game.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 27%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_guild.cpp.o
[ 82%] Linking CXX static library libscripts.a
[ 82%] Built target scripts
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
root@azeroth-app:/azerothcore-wotlk/build#

Second Compile.
Logs
 25%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/BattlegroundMgr.cpp.o
/azerothcore-wotlk/src/server/game/Battlegrounds/BattlegroundMgr.cpp:38:23: fatal error: LuaEngine.h: No such file or directory
compilation terminated.
src/server/game/CMakeFiles/game.dir/build.make:710: recipe for target 'src/server/game/CMakeFiles/game.dir/Battlegrounds/BattlegroundMgr.cpp.o' failed
make[2]: *** [src/server/game/CMakeFiles/game.dir/Battlegrounds/BattlegroundMgr.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 25%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_druid.cpp.o
[ 25%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_dk.cpp.o
CMakeFiles/Makefile2:973: recipe for target 'src/server/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/server/game/CMakeFiles/game.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 25%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_quest.cpp.o
[ 82%] Linking CXX static library libscripts.a
[ 82%] Built target scripts
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
root@azeroth-app:/azerothcore-wotlk/build# 

Compile without the mod: Success.

**Comment by Rochet2** [comment]
Assuming the module is in
`/modules/mod-eluna-lua-engine`

did you fetch the  submodule to 
`/modules/mod-eluna-lua-engine/LuaEngine` ? Does that folder exist? Is it empty?

**Comment by mfranciscojr** [comment]
Hmm it's kinda weird, i fire up another vm and tried again, this time it works.

All required files are on the LuaEngine folder, must be my vm image got bugged. Thanks

root@azeroth-app:/# tree /azerothcore-wotlk/modules/mod-eluna-lua-engine/
/azerothcore-wotlk/modules/mod-eluna-lua-engine/
â”œâ”€â”€ cmake
â”‚Â Â  â”œâ”€â”€ after_gs_install.cmake
â”‚Â Â  â”œâ”€â”€ after_load_conf.cmake
â”‚Â Â  â”œâ”€â”€ after_ws_install.cmake
â”‚Â Â  â”œâ”€â”€ before_gs_install.cmake
â”‚Â Â  â””â”€â”€ before_script_install.cmake
â”œâ”€â”€ CMakeLists.txt
â”œâ”€â”€ conf
â”‚Â Â  â””â”€â”€ mod_LuaEngine.conf.dist
â”œâ”€â”€ _config.yml
â”œâ”€â”€ include.sh
â”œâ”€â”€ LuaEngine
â”‚Â Â  â”œâ”€â”€ AuraMethods.h
â”‚Â Â  â”œâ”€â”€ BattleGroundHooks.cpp
â”‚Â Â  â”œâ”€â”€ BattleGroundMethods.h
â”‚Â Â  â”œâ”€â”€ BindingMap.h
â”‚Â Â  â”œâ”€â”€ CMakeLists.txt
â”‚Â Â  â”œâ”€â”€ CorpseMethods.h
â”‚Â Â  â”œâ”€â”€ CreatureHooks.cpp
â”‚Â Â  â”œâ”€â”€ CreatureMethods.h
â”‚Â Â  â”œâ”€â”€ docs
â”‚Â Â  â”‚Â Â  â”œâ”€â”€ CONTRIBUTING.md
â”‚Â Â  â”‚Â Â  â”œâ”€â”€ DOC_GEN.md
â”‚Â Â  â”‚Â Â  â”œâ”€â”€ ElunaDoc
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ __init__.py
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ __main__.py
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ parser.py
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ static
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ eluna-logo.png
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ favicon.ico
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ FiraSans-Medium.woff
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ FiraSans-Regular.woff
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ Heuristica-Italic.woff
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ jquery.js
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ main.css
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ main.js
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ normalize.css
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ SourceCodePro-Regular.woff
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ SourceCodePro-Semibold.woff
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”‚Â Â  â”œâ”€â”€ SourceSerifPro-Bold.woff
â”‚Â Â  â”‚Â Â  â”‚Â Â  â”‚Â Â  â””â”€â”€ SourceSerifPro-Regular.woff
â”‚Â Â  â”‚Â Â  â”‚Â Â  â””â”€â”€ templates
â”‚Â Â  â”‚Â Â  â”‚Â Â      â”œâ”€â”€ _base.html
â”‚Â Â  â”‚Â Â  â”‚Â Â      â”œâ”€â”€ class.html
â”‚Â Â  â”‚Â Â  â”‚Â Â      â”œâ”€â”€ enum.html
â”‚Â Â  â”‚Â Â  â”‚Â Â      â”œâ”€â”€ index.html
â”‚Â Â  â”‚Â Â  â”‚Â Â      â”œâ”€â”€ method.html
â”‚Â Â  â”‚Â Â  â”‚Â Â      â””â”€â”€ search-index.js
â”‚Â Â  â”‚Â Â  â”œâ”€â”€ Eluna.png
â”‚Â Â  â”‚Â Â  â”œâ”€â”€ IMPL_DETAILS.md
â”‚Â Â  â”‚Â Â  â”œâ”€â”€ INSTALL.md
â”‚Â Â  â”‚Â Â  â”œâ”€â”€ MERGING.md
â”‚Â Â  â”‚Â Â  â””â”€â”€ USAGE.md
â”‚Â Â  â”œâ”€â”€ ElunaCreatureAI.h
â”‚Â Â  â”œâ”€â”€ ElunaEventMgr.cpp
â”‚Â Â  â”œâ”€â”€ ElunaEventMgr.h
â”‚Â Â  â”œâ”€â”€ ElunaIncludes.h
â”‚Â Â  â”œâ”€â”€ ElunaInstanceAI.cpp
â”‚Â Â  â”œâ”€â”€ ElunaInstanceAI.h
â”‚Â Â  â”œâ”€â”€ ElunaQueryMethods.h
â”‚Â Â  â”œâ”€â”€ ElunaTemplate.h
â”‚Â Â  â”œâ”€â”€ ElunaUtility.cpp
â”‚Â Â  â”œâ”€â”€ ElunaUtility.h
â”‚Â Â  â”œâ”€â”€ extensions
â”‚Â Â  â”‚Â Â  â”œâ”€â”€ _Misc.ext
â”‚Â Â  â”‚Â Â  â”œâ”€â”€ ObjectVariables.ext
â”‚Â Â  â”‚Â Â  â””â”€â”€ StackTracePlus
â”‚Â Â  â”‚Â Â      â”œâ”€â”€ LICENSE
â”‚Â Â  â”‚Â Â      â”œâ”€â”€ README.md
â”‚Â Â  â”‚Â Â      â””â”€â”€ StackTracePlus.ext
â”‚Â Â  â”œâ”€â”€ GameObjectHooks.cpp
â”‚Â Â  â”œâ”€â”€ GameObjectMethods.h
â”‚Â Â  â”œâ”€â”€ GlobalMethods.h
â”‚Â Â  â”œâ”€â”€ GossipHooks.cpp
â”‚Â Â  â”œâ”€â”€ GroupHooks.cpp
â”‚Â Â  â”œâ”€â”€ GroupMethods.h
â”‚Â Â  â”œâ”€â”€ GuildHooks.cpp
â”‚Â Â  â”œâ”€â”€ GuildMethods.h
â”‚Â Â  â”œâ”€â”€ HookHelpers.h
â”‚Â Â  â”œâ”€â”€ Hooks.h
â”‚Â Â  â”œâ”€â”€ InstanceHooks.cpp
â”‚Â Â  â”œâ”€â”€ ItemHooks.cpp
â”‚Â Â  â”œâ”€â”€ ItemMethods.h
â”‚Â Â  â”œâ”€â”€ LICENSE
â”‚Â Â  â”œâ”€â”€ lmarshal.cpp
â”‚Â Â  â”œâ”€â”€ lmarshal.h
â”‚Â Â  â”œâ”€â”€ LuaEngine.cpp
â”‚Â Â  â”œâ”€â”€ LuaEngine.h
â”‚Â Â  â”œâ”€â”€ LuaFunctions.cpp
â”‚Â Â  â”œâ”€â”€ MapMethods.h
â”‚Â Â  â”œâ”€â”€ ObjectMethods.h
â”‚Â Â  â”œâ”€â”€ PacketHooks.cpp
â”‚Â Â  â”œâ”€â”€ PlayerHooks.cpp
â”‚Â Â  â”œâ”€â”€ PlayerMethods.h
â”‚Â Â  â”œâ”€â”€ QuestMethods.h
â”‚Â Â  â”œâ”€â”€ README.md
â”‚Â Â  â”œâ”€â”€ ServerHooks.cpp
â”‚Â Â  â”œâ”€â”€ SpellMethods.h
â”‚Â Â  â”œâ”€â”€ UnitMethods.h
â”‚Â Â  â”œâ”€â”€ VehicleHooks.cpp
â”‚Â Â  â”œâ”€â”€ VehicleMethods.h
â”‚Â Â  â”œâ”€â”€ WorldObjectMethods.h
â”‚Â Â  â””â”€â”€ WorldPacketMethods.h
â”œâ”€â”€ lualib
â”‚Â Â  â”œâ”€â”€ CMakeLists.txt
â”‚Â Â  â”œâ”€â”€ lapi.c
â”‚Â Â  â”œâ”€â”€ lapi.h
â”‚Â Â  â”œâ”€â”€ lauxlib.c
â”‚Â Â  â”œâ”€â”€ lauxlib.h
â”‚Â Â  â”œâ”€â”€ lbaselib.c
â”‚Â Â  â”œâ”€â”€ lbitlib.c
â”‚Â Â  â”œâ”€â”€ lcode.c
â”‚Â Â  â”œâ”€â”€ lcode.h
â”‚Â Â  â”œâ”€â”€ lcorolib.c
â”‚Â Â  â”œâ”€â”€ lctype.c
â”‚Â Â  â”œâ”€â”€ lctype.h
â”‚Â Â  â”œâ”€â”€ ldblib.c
â”‚Â Â  â”œâ”€â”€ ldebug.c
â”‚Â Â  â”œâ”€â”€ ldebug.h
â”‚Â Â  â”œâ”€â”€ ldo.c
â”‚Â Â  â”œâ”€â”€ ldo.h
â”‚Â Â  â”œâ”€â”€ ldump.c
â”‚Â Â  â”œâ”€â”€ lfunc.c
â”‚Â Â  â”œâ”€â”€ lfunc.h
â”‚Â Â  â”œâ”€â”€ lgc.c
â”‚Â Â  â”œâ”€â”€ lgc.h
â”‚Â Â  â”œâ”€â”€ linit.c
â”‚Â Â  â”œâ”€â”€ liolib.c
â”‚Â Â  â”œâ”€â”€ llex.c
â”‚Â Â  â”œâ”€â”€ llex.h
â”‚Â Â  â”œâ”€â”€ llimits.h
â”‚Â Â  â”œâ”€â”€ lmathlib.c
â”‚Â Â  â”œâ”€â”€ lmem.c
â”‚Â Â  â”œâ”€â”€ lmem.h
â”‚Â Â  â”œâ”€â”€ loadlib.c
â”‚Â Â  â”œâ”€â”€ lobject.c
â”‚Â Â  â”œâ”€â”€ lobject.h
â”‚Â Â  â”œâ”€â”€ lopcodes.c
â”‚Â Â  â”œâ”€â”€ lopcodes.h
â”‚Â Â  â”œâ”€â”€ loslib.c
â”‚Â Â  â”œâ”€â”€ lparser.c
â”‚Â Â  â”œâ”€â”€ lparser.h
â”‚Â Â  â”œâ”€â”€ lstate.c
â”‚Â Â  â”œâ”€â”€ lstate.h
â”‚Â Â  â”œâ”€â”€ lstring.c
â”‚Â Â  â”œâ”€â”€ lstring.h
â”‚Â Â  â”œâ”€â”€ lstrlib.c
â”‚Â Â  â”œâ”€â”€ ltable.c
â”‚Â Â  â”œâ”€â”€ ltable.h
â”‚Â Â  â”œâ”€â”€ ltablib.c
â”‚Â Â  â”œâ”€â”€ ltm.c
â”‚Â Â  â”œâ”€â”€ ltm.h
â”‚Â Â  â”œâ”€â”€ lua.c
â”‚Â Â  â”œâ”€â”€ luac.c
â”‚Â Â  â”œâ”€â”€ luaconf.h
â”‚Â Â  â”œâ”€â”€ lua.h
â”‚Â Â  â”œâ”€â”€ lua.hpp
â”‚Â Â  â”œâ”€â”€ lualib.h
â”‚Â Â  â”œâ”€â”€ lundump.c
â”‚Â Â  â”œâ”€â”€ lundump.h
â”‚Â Â  â”œâ”€â”€ lvm.c
â”‚Â Â  â”œâ”€â”€ lvm.h
â”‚Â Â  â”œâ”€â”€ lzio.c
â”‚Â Â  â””â”€â”€ lzio.h
â”œâ”€â”€ ObjectGuid.h
â”œâ”€â”€ README_CN.md
â”œâ”€â”€ README.md
â””â”€â”€ sql
    â”œâ”€â”€ auth
    â”œâ”€â”€ characters
    â””â”€â”€ world

14 directories, 157 files
root@azeroth-app:/#
