### ISSUE TITLE
Player:UnbindAllInstances() Stop Server

### ISSUE THREAD

**Issue by Racknar0** [azerothcore/mod-eluna-lua-engine#32]
when it's used
player: UnbindAllInstances () crashes the server

and when using http://elunaluaengine.github.io/Player/UnbindAllInstances.html

Player: UnbindAllInstances ()

It does not work

Thanks a lot

**Comment by FrancescoBorzi** [comment]
@Rochet2

**Comment by newrage** [comment]
here the fix for the Player: UnbindAllInstances ()
[fix Player UnbindAllInstances.zip](https://github.com/azerothcore/mod-eluna-lua-engine/files/5812766/fix.Player.UnbindAllInstances.zip)

your welcome

**Comment by FrancescoBorzi** [comment]
@newrage please create a PR with the fix, we can assist you if needed

**Comment by newrage** [comment]
i do not know how to do that but i know it works

**Comment by FrancescoBorzi** [comment]
@newrage you can follow this (but keep in mind that your target is not the main repo but the `mod-eluna-lua-engine` instead: https://www.azerothcore.org/wiki/How-to-create-a-PR

**Comment by Rochet2** [comment]
Fixed in https://github.com/ElunaLuaEngine/Eluna/commit/dc05a4b4aa23dc5b57c83d99b3b79a0e5db15af5
