### ISSUE TITLE
On latest commit this date, os_tmpname is dangerous

### ISSUE THREAD

**Issue by Psilovybin** [azerothcore/mod-eluna-lua-engine#4]
Seems like it compiles fine but at the end shows up this error:
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../../../modules/mod-eluna-lua-engine/lualib/liblualib.a(loslib.c.o): in function `os_tmpname':
loslib.c:(.text+0x874): warning: the use of `tmpnam' is dangerous, better use `mkstemp'

**Comment by Rochet2** [comment]
it is a warning, not an error. I think it occurs on linux only.
To fix the warning the lualib would need additional flags. Someone commented that

> Use LUA_USE_POSIX flag to compile. The recomended way is to use LUA_USE_LINUX but that would fail without adding libdl

**Comment by FrancescoBorzi** [comment]
```
../../../modules/mod-eluna-lua-engine/lualib/liblualib.a(loslib.c.o): In function `os_tmpname':
loslib.c:(.text+0x86c): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
```

still getting it in the travis pipeline of the main repository

**Comment by Rochet2** [comment]
Fixed in https://github.com/azerothcore/mod-eluna-lua-engine/issues/17
Create new issue if needed.
