### ISSUE TITLE
Unable to successfully compile using Eluna Engine Mod

### ISSUE THREAD

**Issue by arielcami** [azerothcore/mod-eluna-lua-engine#40]
Error in VS when using this module.

commit a278fd734014a4e7c70a134ed9af43eae525b2e6

![lua engine error](https://user-images.githubusercontent.com/71854140/115412979-6f67e180-a1ba-11eb-9da7-4f67abf46963.png)

**Comment by FrancescoBorzi** [comment]
@arielcami have you tried updating the Eluna version? from the readme:

> if you need to update Eluna to the latest version, you can cd LuaEngine and run git pull from there.

**Comment by arielcami** [comment]
Yes, I've updated Eluna module to the latest version.
