### ISSUE TITLE
Suggestion: update readme to include instructions for AzerothCore's Docker instructions

### ISSUE THREAD

**Issue by suprsokr** [azerothcore/mod-eluna-lua-engine#42]
This would include:

- A section for where to put the mod_LuaEngine.conf and mod_LuaEngine.conf.dist files (https://www.azerothcore.org/wiki/Install-with-Docker#adding-modules has been updated to show that `azerothcore-wotlk/env/docker/etc/modules` is the proper location, but having it on this page might also be useful)
- Where to set the `Eluna.ScriptPath` value. [This stackoverflow post](https://stackoverflow.com/questions/64564961/setting-up-lua-scripts-directory-for-azerothcore-docker-build/67452598#67452598) is a great resource. I am not good enough with Docker to explain how to expose a volume using the `docker-compose.yml` file, but a good start would be just telling people to set the ScriptPath to `Eluna.ScriptPath = "/azerothcore/lua_scripts"` and creating a `lua_scripts` folder in their `azerothcore-wotlk` folder.

If the current maintainers like this idea, I can create a PR that updates the readme.

**Comment by Helias** [comment]
@Yehonal

**Comment by Yehonal** [comment]
So the issue is that we don't expose the bin folder anymore and that the lua_scripts reside under the bin folder. We can for sure provide a volume for them by default, but I was wondering: is the a configuration for Eluna to change that path?

**Comment by suprsokr** [comment]
Eluna.ScriptPath is the configuration in Eluna that tells it where to look for the lua_scripts folder. Perhaps this is enough?
