### ISSUE TITLE
Bug in Say() method

### ISSUE THREAD

**Issue by DamianBajofer** [azerothcore/mod-eluna-lua-engine#45]
Hey, i have the latest reversion of AzerothCore and i am having an problem with the method **Say()**

I download azeroth core 3 days ago and eluna too!

This is the result
![1](https://user-images.githubusercontent.com/52859523/120103777-b20cca00-c127-11eb-8742-28e92b5d2866.png)
![2](https://user-images.githubusercontent.com/52859523/120103779-b33df700-c127-11eb-8c6d-65f433e69bf8.png)
![3](https://user-images.githubusercontent.com/52859523/120103783-b76a1480-c127-11eb-8fdf-57d0f993b4a3.png)

Any solution?

**Comment by Helias** [comment]
print the hash commit of:
- azerothcore
- mod-eluna-lua-engine
- LuaEngine

to get it you can go to the directory, write `git log`:
![image](https://user-images.githubusercontent.com/519778/120108514-be177c80-c165-11eb-9651-c13340fa36c4.png)

same for ac and LuaEngine directory

**Comment by DamianBajofer** [comment]
I haven't `.git` directory in my source or eluna-engine.. then i cant use `git log`

**Comment by ralver** [comment]
Your script is registring to the chat and when you send something with say you trigger it again. This is causing the endless loop. 
You need to update the local function with global variable to check if the say is an original one and not a new one. 

```
local send_say=false
local function OnPlayerChat(event, player, message, msgType, language)
    if not send_say then
        player:Say(message.." : OTHER", language)
        send_say = true
    else
        send_say = false
    end
    return false
end.

RegisterPlayerEvent(18, OnPlayerChat)
```

**Comment by Rochet2** [comment]
The hook can return false to intercept the original message, but it can also return a new message that replaces the original message in addition to that.
While above solution works, it might be cleaner to use the return value to modify the original message.
Here is an example:
```lua
local function OnPlayerChat(event, player, message, msgType, language)
    return nil, message.." : OTHER"
end
RegisterPlayerEvent(18, OnPlayerChat)
```

Closing this as there are few solutions posted to the problem.
