### ISSUE TITLE
Error compiling Lua engine on AC

### ISSUE THREAD

**Issue by WillzDevs** [azerothcore/mod-eluna-lua-engine#49]
CMAKE ok.
When going to compile the error in GlobalMethods.h in lines 2122 and 2148.
As in the image below:
![image](https://user-images.githubusercontent.com/67213916/123165478-aa9cc000-d44a-11eb-8774-f01f6ab8efdb.png)

**Comment by tkn963** [comment]
It seems to be related to https://github.com/azerothcore/azerothcore-wotlk/commit/9ac6fddcae9837f468f52369f0f963da7c41569a but I might be wrong.

The current solution is to update LuaEngine manually until it gets fixed.

**Comment by WillzDevs** [comment]
> It seems to be related to [azerothcore/azerothcore-wotlk@9ac6fdd](https://github.com/azerothcore/azerothcore-wotlk/commit/9ac6fddcae9837f468f52369f0f963da7c41569a) but I might be wrong.
> 
> The current solution is to update LuaEngine manually until it gets fixed.
It has something to do with #6015 Kitzunu was correcting tonight... thanks for the return 😁

**Comment by WillzDevs** [comment]
@Helias does this have to do with the latest updates?

**Comment by Helias** [comment]
I think so, I encountered an issue to compile eluna module too

**Comment by WillzDevs** [comment]
> I think so, I encountered an issue to compile eluna module too

Yes, the same is happening with the npc free professions module, SkillLineAbilityEntry error.
I appreciate your work, wonderful!

**Comment by Helias** [comment]
I saw even that, but that's related of a @Kitzunu PR

**Comment by WillzDevs** [comment]
> I saw even that, but that's related of a @Kitzunu PR

ok, let's wait then

**Comment by FrancescoBorzi** [comment]
it should be fixed now, if not please let us know and I'll reopen this

**Comment by FrancescoBorzi** [comment]
it should be fixed now. Please update your Eluna to the latest version and try again. If this is still a problem, please let us know and I'll reopen this

**Comment by WillzDevs** [comment]
> it should be fixed now. Please update your Eluna to the latest version and try again. If this is still a problem, please let us know and I'll reopen this

I've updated it and it's working perfectly!!! Thank you very much!!!
@FrancescoBorzi Do you think it is necessary for me to open an issue in the npc professions module about the problem in SkillLineAbilityEntry?

**Comment by FrancescoBorzi** [comment]
> > it should be fixed now. Please update your Eluna to the latest version and try again. If this is still a problem, please let us know and I'll reopen this
> 
> I've updated it and it's working perfectly!!! Thank you very much!!!
> @FrancescoBorzi Do you think it is necessary for me to open an issue in the npc professions module about the problem in SkillLineAbilityEntry?

yes please!

**Comment by WillzDevs** [comment]
> > > it should be fixed now. Please update your Eluna to the latest version and try again. If this is still a problem, please let us know and I'll reopen this
> > 
> > 
> > I've updated it and it's working perfectly!!! Thank you very much!!!
> > @FrancescoBorzi Do you think it is necessary for me to open an issue in the npc professions module about the problem in SkillLineAbilityEntry?
> 
> yes please!

Ah, it's already been fixed today, several modules were updated today! Thanks!
