### ISSUE TITLE
PLAYER_EVENT_ON_SPELL_CAST doesn't work.

### ISSUE THREAD

**Issue by Makpptfox** [azerothcore/mod-eluna-lua-engine#5]
Hi, 

I just figured out that the PLAYER_EVENT_ON_SPELL_CAST doesn't work, I only have the Eluna module installed on my Acore.

I tried to test with a very simple script, and saddly nothing happenned.

```
local function testcast(event, player, spell)
local spell = spell:GetEntry()
	if spell == 48785 then
		player:CastSpell(self, 642, true)
	end
end


RegisterPlayerEvent(5, testcast)
```

**Comment by AyaseCore** [comment]
sorry, I didn't have time to check this issue until now.

```
void ScriptMgr::OnPlayerSpellCast(Player* player, Spell* spell, bool skipCheck)
{
#ifdef ELUNA
    sEluna->OnSpellCast(player, spell, skipCheck);
#endif
    FOREACH_SCRIPT(PlayerScript)->OnSpellCast(player, spell, skipCheck);
}
```

But unfortunately,this hook does not seem to be used.
https://github.com/azerothcore/azerothcore-wotlk/blob/23d78ce6bc75af53a49d12e5823f152b335df2a7/src/server/game/Spells/Spell.cpp#L3646

**Comment by Makpptfox** [comment]
Is it fixable with keeping the module in mind, or do it require to change the spell.cpp itself with a patch ?
Because this hook is pretty useful, for a lot of things.

**Comment by AyaseCore** [comment]
Modules need to rely on hooks.
So if the hook itself doesn't work (such as being commented-out),modules certainly can't fix it.
We can only change the spell.cpp.

So you can try opening a PR to change it. :)
https://github.com/azerothcore/azerothcore-wotlk/pulls

**Comment by BarbzYHOOL** [comment]
Just uncomment it and add the cmake EXTRAS tags (so we keep the "optimization" thinking process of sunwell devs)

I'm referring to this: `option(ENABLE_EXTRAS "Set to 0 to disable extra features optimizing performances" 1)` listed here https://github.com/azerothcore/azerothcore-wotlk/blob/master/conf/config.cmake.dist

**Comment by BarbzYHOOL** [comment]
I mean for the azerothcore PR

**Comment by wizzymore** [comment]
This was fixed on https://github.com/azerothcore/azerothcore-wotlk/pull/1624
