### ISSUE TITLE
Compilation error on AC

### ISSUE THREAD

**Issue by SaidKing** [azerothcore/mod-eluna-lua-engine#53]
When I go to compile the eluna-module I get the following error: C2664, in the file MapMethods.h
![image](https://user-images.githubusercontent.com/75864589/131998083-cdd7950e-cb40-4bee-a63b-551f84fcdbe7.png)

**Comment by FrancescoBorzi** [comment]
@SaidKing you need to update your Eluna version

>  if you need to update Eluna to the latest version, you can cd LuaEngine and run git pull from there.

**Comment by SaidKing** [comment]
> @SaidKing você precisa atualizar sua versão Eluna
> 
> > se você precisar atualizar Eluna para a versão mais recente, você pode cd LuaEngine e executar git pull a partir daí.

I'm already using the latest version of Eluna, but I can't compile it.

**Comment by FrancescoBorzi** [comment]
@SaidKing have you tried running `cd LuaEngine` and then run `git pull` from there ?
