### ISSUE TITLE
Error in MapMethods.h when compiling core

### ISSUE THREAD

**Issue by zanzaqtlol** [azerothcore/mod-eluna-lua-engine#54]
I updated my core to the latest version of Azeroth core, but after updating when I went to compile an error occurred in MapMethods.h in Lua.Engine, below is the image of the error:

![image](https://user-images.githubusercontent.com/23637989/132150235-081502bb-2032-4a10-bca8-77117d12e57d.png)

**Comment by Racknar0** [comment]
Error compile

![image](https://user-images.githubusercontent.com/38267074/132384977-ec9729bc-c256-4090-ba8c-6ce673ad8f01.png)

**Comment by FrancescoBorzi** [comment]
you need to update your eluna version to latest

> if you need to update Eluna to the latest version, you can cd LuaEngine and run git pull from there.

**Comment by zanzaqtlol** [comment]
> you need to update your eluna version to latest
> 
> > if you need to update Eluna to the latest version, you can cd LuaEngine and run git pull from there.

you closed the topic but I updated to the latest version and the error MapMethods.h continues!

**Comment by Rochet2** [comment]
@zanzaqtlol
Based on the code in the error message and the file lines you are using an old version.
Where did you get Eluna from?
How are you updating it to latest version?

**Comment by zanzaqtlol** [comment]
> Based on the code in the error message and the file lines you are using an old version.
> Where from or how did you get Eluna?
> How are you updating it to latest version?

I'm updating in pull, by Git Extensions>Pull
![image](https://user-images.githubusercontent.com/23637989/132766396-30814933-917c-4f84-b02f-2eb52e633df3.png)

**Comment by Winfidonarleyan** [comment]
> you need to update your eluna version to latest

**Comment by Rochet2** [comment]
Try the following console commands (in cmd or git bash) while the console is in the mod-eluna-lua-engine folder.
This shows us the current remote and branch information. It could be that they point to the wrong location.
```
git remote -vvvvv
git branch -vvvvv
```
