### ISSUE TITLE
在 azerothcore version:4.0.0-dev.11中， Compilation failed 禁止显示状态 错误C2660

### ISSUE THREAD

**Issue by ssdphp** [azerothcore/mod-eluna-lua-engine#56]
在 azerothcore {
  "name": "azerothcore-wotlk",
  "version": "4.0.0-dev.11",
  "license": "AGPL3"
}

Compilation failed
![QQ截图20210925023033](https://user-images.githubusercontent.com/16387049/134723625-53a10917-78e0-4737-9387-ac61e5d52caa.png)

15>D:\wow\azerothcore-wotlk\modules\mod-eluna-lua-engine-master\LuaEngine\UnitMethods.h(2817,43): error C2660: “Unit::CalcAbsorbResist”: 函数不接受 1 个参数 (编译源文件 D:\wow\azerothcore-wotlk\modules\mod-eluna-lua-engine-master\LuaEngine\LuaFunctions.cpp)

15>D:\wow\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(2299,17): message : 参见“Unit::CalcAbsorbResist”的声明 (编译源文件 D:\wow\azerothcore-wotlk\modules\mod-eluna-lua-engine-master\LuaEngine\LuaFunctions.cpp)
15>D:\wow\azerothcore-wotlk\modules\mod-eluna-lua-engine-master\LuaEngine\UnitMethods.h(2839,88): error C2664: “SpellNonMeleeDamage::SpellNonMeleeDamage(Unit *,Unit *,uint32,uint32)”: 无法将参数 3 从“const SpellInfo *”转换为“uint32” (编译源文件 D:\wow\azerothcore-wotlk\modules\mod-eluna-lua-engine-master\LuaEngine\LuaFunctions.cpp)
15>D:\wow\azerothcore-wotlk\modules\mod-eluna-lua-engine-master\LuaEngine\UnitMethods.h(2839,51): message : 没有使该转换得以执行的上下文 (编译源文件 D:\wow\azerothcore-wotlk\modules\mod-eluna-lua-engine-master\LuaEngine\LuaFunctions.cpp)
15>D:\wow\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1012,5): message : 参见“SpellNonMeleeDamage::SpellNonMeleeDamage”的声明 (编译源文件 D:\wow\azerothcore-wotlk\modules\mod-eluna-lua-engine-master\LuaEngine\LuaFunctions.cpp)
15>D:\wow\azerothcore-wotlk\modules\mod-eluna-lua-engine-master\LuaEngine\UnitMethods.h(2888,49): error C2660: “Unit::HealBySpell”: 函数不接受 2 个参数 (编译源文件 D:\wow\azerothcore-wotlk\modules\mod-eluna-lua-engine-master\LuaEngine\LuaFunctions.cpp)
15>D:\wow\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1783,11): message : 参见“Unit::HealBySpell”的声明 (编译源文件 D:\wow\azerothcore-wotlk\modules\mod-eluna-lua-engine-master\LuaEngine\LuaFunctions.cpp)

**Comment by yuanf225** [comment]
`[ 34%] Building CXX object src/server/game/CMakeFiles/game.dir/Entities/Player/PlayerQuest.cpp.o
/home/azerothcore-wotlk/src/server/game/Entities/Player/Player.cpp:12686:56: fatal error: conversion from 'ObjectGuid' to 'uint64' (aka 'unsigned long') is ambiguous
        sEluna->OnLootItem(this, newitem, item->count, this->GetLootGUID());
                                                       ^~~~~~~~~~~~~~~~~~~
/home/azerothcore-wotlk/src/server/game/Entities/Object/ObjectGuid.h:195:9: note: candidate function
        operator bool() const { return !IsEmpty(); }
        ^
/home/azerothcore-wotlk/src/server/game/Entities/Object/ObjectGuid.h:239:9: note: candidate function has been explicitly deleted
        operator int64() const = delete;
        ^
/home/azerothcore-wotlk/modules/mod-eluna-lua-engine/LuaEngine/LuaEngine.h:348:72: note: passing argument to parameter 'guid' here
    void OnLootItem(Player* pPlayer, Item* pItem, uint32 count, uint64 guid);
                                                                       ^
[ 34%] Building CXX object src/server/game/CMakeFiles/game.dir/Entities/Player/PlayerStorage.cpp.o
1 error generated.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:1234: src/server/game/CMakeFiles/game.dir/Entities/Player/Player.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 34%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_reset.cpp.o
`  Compiling in the classic way will also cause an error

**Comment by Helias** [comment]
Update core and mod-eluna-lua-engine to last version
update also the LuaEngine directory
