### ISSUE TITLE
Compile issue on latest commit Latest commit cbc0c93

### ISSUE THREAD

**Issue by milestorme** [azerothcore/mod-eluna-lua-engine#7]
Build errors with eluna-mod on latest commit cbc0c93

`In file included from /var/michael/azerothcore-wotlk/src/common/Collision/Management/VMapManager2.cpp:30:
In file included from /var/michael/azerothcore-wotlk/src/server/game/DataStores/DBCStores.h:11:
/var/michael/azerothcore-wotlk/src/common/DataStores/DBCStore.h:317:9: error: no template named
      'unordered_map' in namespace 'std'; did you mean 'std::tr1::unordered_map'?
        std::unordered_map<uint32, T const*> data;
        ^~~~~~~~~~~~~~~~~~
        std::tr1::unordered_map
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/tr1/unordered_map.h:180:11: note:
      'std::tr1::unordered_map' declared here
    class unordered_map
          ^
In file included from /var/michael/azerothcore-wotlk/src/common/Collision/Management/VMapManager2.cpp:30:
In file included from /var/michael/azerothcore-wotlk/src/server/game/DataStores/DBCStores.h:11:
/var/michael/azerothcore-wotlk/src/common/DataStores/DBCStore.h:78:26: error: no template named
      'unordered_map' in namespace 'std'; did you mean 'std::tr1::unordered_map'?
                typename std::unordered_map<uint32, T const*>::const_iterator it = data.find(id);
                         ^~~~~~~~~~~~~~~~~~
                         std::tr1::unordered_map
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/tr1/unordered_map.h:180:11: note:
      'std::tr1::unordered_map' declared here
    class unordered_map
          ^
[ 20%] Building CXX object src/common/Collision/CMakeFiles/collision.dir/Maps/TileAssembler.cpp.o
2 errors generated.`

**Comment by milestorme** [comment]
this is on x64 Debian 9 build, still continues to fail with same error, fresh git pull on core and module

**Comment by Rochet2** [comment]
try add `#include <unordered_map>`
to the top of `DBCStores.h`

**Comment by milestorme** [comment]
Thank you rochet2 , legend , build successful , I will submit a PR
