### ISSUE TITLE
RegisterCreatureEvent does not fire

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/mod-eluna-lua-engine#73]
`RegisterCreatureEvent` does nothing. It executes the command without an error, but the events never happen. Tested for `OnEnterCombat`, `OnLeaveCombat` and `OnDied`.

8371e85248ab 2021-12-08 08:22:48 +0000 (master branch) (Win64, RelWithDebInfo, Static)
I tried the same script with a compiled version from Nov 13th and it worked fine.

mod-eluna: f68d83e8c6ecf64844a42aaa8ad25cb8aa0a3a17

**Comment by yuanf225** [comment]
The current version of the module seems to cause the problem that AIO cannot be used，
Do I need to start a new case?
