### ISSUE TITLE
Eluna won't compile " isEmpty not a member of Map" 

### ISSUE THREAD

**Issue by temperrr** [azerothcore/mod-eluna-lua-engine#80]
![image](https://user-images.githubusercontent.com/20357406/149493867-ceb02146-db11-41fa-ba33-d5bede5c6136.png)

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	1 unresolved externals	worldserver	F:\Build\bin\RelWithDebInfo\worldserver.exe	1	
Error	C2039	'isEmpty': is not a member of 'Map' (compiling source file H:\Azerothcore\modules\mod-eluna-lua-engine\src\LuaEngine\LuaFunctions.cpp)	modules	H:\Azerothcore\modules\mod-eluna-lua-engine\src\LuaEngine\MapMethods.h	66	
Message		see declaration of 'Map' (compiling source file H:\Azerothcore\modules\mod-eluna-lua-engine\src\LuaEngine\LuaFunctions.cpp)	modules	H:\Azerothcore\src\server\game\Instances\InstanceScript.h	31	
Error	LNK2019	unresolved external symbol "private: bool __cdecl ReputationMgr::SetReputation(struct FactionEntry const *,float,bool,bool,class std::optional<enum ReputationRank>)" (?SetReputation@ReputationMgr@@AEAA_NPEBUFactionEntry@@M_N1V?$optional@W4ReputationRank@@@std@@@Z) referenced in function "int __cdecl LuaPlayer::SetReputation(struct lua_State *,class Player *)" (?SetReputation@LuaPlayer@@YAHPEAUlua_State@@PEAVPlayer@@@Z)	worldserver	F:\Build\src\server\worldserver\modules.lib(LuaFunctions.obj)	1	
`

**Comment by luolingjun** [comment]
IsEmpty
