### ISSUE TITLE
Core refactor breaks compilation (isEmpty -> IsEmpty)

### ISSUE THREAD

**Issue by funar** [azerothcore/mod-eluna-lua-engine#82]
This commit has broken compilation of mod-eluna-lua-engine:

refactor(Core/Misc): isEmpty to IsEmpty (#10011) 
https://github.com/azerothcore/azerothcore-wotlk/commit/d1cc65b1c742a3000d3fd05c6a0c40029f1c4d1c

**Comment by Helias** [comment]
thanks to this https://github.com/azerothcore/mod-eluna-lua-engine/pull/81 this issue can be closed now
