### ISSUE TITLE
CC PTR crash 18/01/2022

### ISSUE THREAD

**Issue by temperrr** [azerothcore/mod-eluna-lua-engine#83]
Rev: 124ea8a1e7d0

Modules;
mod-anticheat
mod-autobalance
mod-cfbg
mod-chromie-xp
mod-desertion-warnings
mod-duel-reset
mod-ip-tracker
mod-eluna-lua-engine
mod-low-level-arena
mod-progression-system
mod-pvp-titles
mod-pvpstats-announcer
mod-queue-list-cache
mod-rdf-expansion
mod-server-auto-shutdown
mod-spellsystem-extended

Operating system
Unix

See pastebin
https://pastebin.com/8ErBP7F5

**Comment by Winfidonarleyan** [comment]
Start work
